### ISSUE TITLE
Branch team 5 with team 2

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#103]
This is so they can utilize our alias creation/connection gui. Not sure if they actually want to branch, but I figure this is the best way to explain it.

**Comment by rsanchez-wsu** [comment]
@ltlindon I cannot tell from your description what this issue is meant to accomplish.  Could you elaborate?  Is the objective to create a new branch, merge two existing branches, or merge then create new branch?  Or perhaps something else entirely?

**Comment by ltlindon** [comment]
The gist of this issue, is to give team 2 our connection GUI so they can test there SQL window with alias log in capabilities.

**Comment by rsanchez-wsu** [comment]
So you want to merge the Team-5 branch into the Team-2 branch so that Team 2 has your GUI code?  If that is so, please update the title and description of the issue to more accurately reflect that.  Also, you need to decide if you will assign it to someone on your team or on Team 2.  It might make sense for this issue to go to Team 2 and move to their milestone since they are likely going to have an easier time merging code coming into your branch than you or someone on your team will have trying to merge into another team's branch.

**Comment by ltlindon** [comment]
this was finished
