### ISSUE TITLE
Establish and Maintain a Secure Connection with the Database

### ISSUE THREAD

**Issue by mgross99** [rsanchez-wsu/sp16-ceg3120#6]
In order to work with the database we set up, we need to create a secure connection that handles errors. We also need to set up local host and acquire the port number for our interface to run.

**Comment by rsanchez-wsu** [comment]
@mgross99 Recall that if we use Derby it is likely going to be in embedded mode.  That means that there will not be a database server to which a connection needs to be made.  The derby.jar will establish the connection by accessing the database you specify at some on-disk location.  Because of that, Derby will not provide any security, since security is handled via filesystem permissions.

**Comment by mgross99** [comment]
@rsanchez-wsu I did not know that. Sorry. I updated the comment to more effectively address our issue, without referencing to the Derby server.
