### ISSUE TITLE
Issue 2. Create test database. T3-M1

### ISSUE THREAD

**Issue by rtschock** [rsanchez-wsu/sp16-ceg3120#7]
Issue 2- Create database to test connection between GUI and Enterprise server. T3-M1

**Comment by mspehar** [comment]
I think having an idea of what the database is designed to store would go a long way to allowing people to feel comfortable about this project.

**Comment by rsanchez-wsu** [comment]
@rtschock Two items to point out:
- Please don't number issues in the title.  GitHub handles issue number automatically (this one is #7, for instance)
- Please make sure you read the [development process](https://github.com/rsanchez-wsu/sp16-ceg3120/wiki/Development-Process) wiki page and assign the appropriate tags (priority, state, type, and team)

**Comment by rsanchez-wsu** [comment]
@mspehar The current application concept is for a generic database browser application.  It shouldn't and doesn't matter what is stored in the database.  The idea is that the application will allow you to establish a connection to a database, then it will read, display, and let you otherwise interact with the contents of the database.

**Comment by rtschock** [comment]
Helped implement new databases.
