### ISSUE TITLE
Merge successfully with Team-6-Carl-Annie's branch from Team-6 branch

### ISSUE THREAD

**Issue by alisonguyton** [rsanchez-wsu/sp16-ceg3120#78]
This needs questions answered. Believe it to be done, Team-6-Carl-Annie's branch might have merged with Team-6 or visa versa,

**Comment by rsanchez-wsu** [comment]
@CHeritage Since you have closed this issue, is it appropriate to change the state from awaiting verification to done?  If so, please do so.  Also, if the Team-6-Carl-Annie branch has been merged back into the Team-6 branch, please consider deleting the now obsolete branch.  If you do delete the branch, don't forget to also delete it on the remote.
