### ISSUE TITLE
Remove latest push to team 6 branch.

### ISSUE THREAD

**Issue by GashMcNash** [rsanchez-wsu/sp16-ceg3120#99]
It has errors in it and I want to revert the branch.

**Comment by rsanchez-wsu** [comment]
@GashMcNash This issue is useless.  At a minimum you need to identify the specific Git commit to revert.  However, it looks like as the time I write this comment that the team 6 branch is successfully building on Jenkins.  If this is no longer a problem, please go ahead and close the issue.  If you think there is still a problem to resolve, improve the description, add a state label, assign the issue, and add it to a milestone.

**Comment by rsanchez-wsu** [comment]
@alisonguyton Did you close this because it was invalid?  If so, please update the label.

**Comment by alisonguyton** [comment]
@rsanchez-wsu  I closed it because you said the issue was useless and your questions to whether is was done or not was never answered. I am not sure if it is done or not myself but since no one is responding I guess it would be considered an invalid issue.

**Comment by rsanchez-wsu** [comment]
@alisonguyton That works for me.  Thanks for following up.
